//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diamond_Addon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public string Id { get; set; }
        public string DocEntry { get; set; }
        public string DocNum { get; set; }
        public string ObjType { get; set; }
        public string DateTime { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string IsOpen { get; set; }
        public string UserId { get; set; }
        public string CompanyId { get; set; } 
    }
}
